name: VPC CI

on:
  pull_request:
    branches: [main]
    paths:
      - "infra/network/**"
      - ".github/workflows/vpc-ci.yml"

permissions:
  contents: read
  id-token: write

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/network

    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TF_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init -reconfigure -backend-config=backend.hcl
      - run: terraform fmt -recursive -check -diff
      - run: terraform validate
      - run: terraform plan -var="aws_region=${{ vars.AWS_REGION }}" -var="environment=dev"